project:
  type: book
  output-dir: output

bibliography: assets/references.bib
execute:
  echo: false
  output: true
highlight-style: assets/monochrome-bold.theme
number-sections: true
toc: true

book:
  title: OpenRFSense
  author: Leonardo Baldin
  date: 15/03/2023
  chapters:
    - index.qmd
    - chapters/introduction.qmd
    # - chapters/appendices.qmd
    - chapters/bibliography.qmd

format:
  unitn-thesis-pdf:
    bachelors: Computer Science
    year: 2021/2022
    supervisor: Fabrizio Granelli
    keep-tex: false
    # Indent paragraphs instead of adding space between them
    indent: true
    mainfont: TeX Gyre Pagella
    monofontoptions:
      - Scale=0.9
  html:
    theme: cosmo

filters:
  - custom-appendices
  - d2

d2:
  path: bin/d2/bin/d2
